-- Detalle diario de compras (derivado del reporte "Detalle de Compras por Artículo" de Tango).
-- Una fila por (fecha, artículo, proveedor). Alimenta la vista "Por día/semana" del módulo
-- Informes de Compras. Se reemplaza por mes al reimportar.
create table if not exists public.compras_detalle_import (
  id          bigint generated by default as identity primary key,
  period      text not null,        -- 'YYYY-MM'
  fecha       date not null,
  code        text,                 -- código de artículo
  description text,
  proveedor   text,
  cantidad    numeric not null default 0,
  importe     numeric not null default 0
);
create index if not exists compras_detalle_import_period on public.compras_detalle_import (period);
create index if not exists compras_detalle_import_period_fecha on public.compras_detalle_import (period, fecha);

alter table public.compras_detalle_import disable row level security;
grant all on public.compras_detalle_import to anon, authenticated;
